[package]
name = "anemulator"
version = "0.1.0"
authors = ["Justin (:flaviusb) Marsh <justin.marsh@flaviusb.net>"]

[dependencies]
tokio = "0.1.7"
futures = "^0.1.20"
anemulator_hardware = { version = "0.1.0", path = "../anemulator_hardware" }
